### ISSUE TITLE
docs?

### ISSUE THREAD

**Issue by hyusetiawan** [f5io/jsonpath#1]
would love to try this out, but I am not sure if the api is the same as the https://github.com/dchester/jsonpath or not, does it have apply()?

**Comment by f5io** [comment]
@hyusetiawan Hi, apologies for the lack of documentation. I haven't really found the time yet.

This library has a very simple API which contains one method `query(<query>, <obj>)`, Unfortunately, it does not have all the niceties around returning paths. It very much only focuses on the results of a query, rather than where those results were found. It does however support a few extensions on the usual JSONPath implementation, which allow things like the [apply](https://github.com/dchester/jsonpath#jpapplyobj-pathexpression-fn) example. To achieve the same result, you should be able to do something like:

``` javascript
import query from '@f5io/jsonpath';

const obj = { ... } // the object to be queried
const results = query('$..author[!(@.toUpperCase())]', obj);
```

As you can see, the `[!(..)]` syntax is a simple map expression.

I appreciate the libraries focus on pure results might not be for everyone's use-case, however this was developed as a basis for my simple [jsont](https://github.com/f5io/jsont) implementation.

I hope this helps. I promise I will get down to doing docs as soon as I have some time. Let me know if I can help with anything else.

**Comment by hyusetiawan** [comment]
i end up using the library and write a simple wrapper around it, luckily the library returns the same referenced objects in the result as in the passed in object to be queried so i can just apply() over those. Knowing the limitation I can't mutate primitives but i have to return the enclosing object, but i'll live :)
Of all the jsonpath i've tried, this is the easiest to get started with, the others i've tried have not been easy to setup.

Thanks!

**Comment by f5io** [comment]
Ah, sorry, I missed the mutate bit. Yes, returning the enclosing object and mutating there is a good solution.
